# Generated by Django 6.0.7 on 2026-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_conversationmessage_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
